[package]
name = "qrious"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 1

[dependencies]
image = "0.25.2"
anyhow = "1.0.86"
base64 = "0.22.1"
maud = "0.26.0"
xml-rs = "0.8.20"
approx = "0.5.1"
clap = { version = "4.5.11", features = ["derive"] }
